import { describe, expect, it } from 'vitest'
import {
  bindChmlFrpIniLocalPort,
  createChmlFrpIni,
  parseChmlFrpIni,
  parseChmlFrpSettings,
  parseFrpSettings,
  parseFrpTransportSettings,
} from '../src/frp-config.js'

/** Verbatim frpc.ini as generated by the ChmlFrp panel (see manual verification). */
const PANEL_INI = `[common]
server_addr = 23.147.68.16
server_port = 7000
tls_enable = false
user = 7iisbpYDIRLSmHqOcN8qwZDa
token = ChmlFrpToken

[dsh_mobile]
type = https
local_ip = 127.0.0.1
local_port = 443
custom_domains = dsh.cwlindean.top
`

describe('ChmlFrp transport configuration', () => {
  it('parses the panel-generated frpc.ini verbatim', () => {
    const settings = parseChmlFrpIni(PANEL_INI)
    expect(settings).toEqual({
      version: 1,
      kind: 'chmlfrp',
      serverAddress: '23.147.68.16',
      serverPort: 7000,
      user: '7iisbpYDIRLSmHqOcN8qwZDa',
      token: 'ChmlFrpToken',
      publicOrigin: 'https://dsh.cwlindean.top',
    })
  })

  it('accepts the short shared platform token that the self-hosted path rejects', () => {
    // 'ChmlFrpToken' is 12 characters; the private-frps rule demands 16.
    const chmlfrp = { kind: 'chmlfrp', serverAddress: '23.147.68.16', serverPort: 7000, user: '7iisbpYDIRLSmHqOcN8qwZDa', token: 'ChmlFrpToken', publicOrigin: 'https://dsh.cwlindean.top' }
    expect(parseChmlFrpSettings(chmlfrp).token).toBe('ChmlFrpToken')
    // Same token, self-hosted shape: rejected by the high-entropy rule.
    expect(() => parseFrpSettings({
      serverAddress: 'frp.example.com', serverPort: 7000, token: 'ChmlFrpToken', publicOrigin: 'https://dsh.example.com',
    })).toThrow('frp_token_invalid')
    // A self-hosted payload must not smuggle the ChmlFrp-only `user` field.
    expect(() => parseFrpSettings({ ...chmlfrp, kind: 'self-hosted' })).toThrow('frp_settings_invalid')
  })

  it('rejects unsafe user ids and malformed origins', () => {
    const base = { kind: 'chmlfrp', serverAddress: '23.147.68.16', serverPort: 7000, user: '7iisbpYDIRLSmHqOcN8qwZDa', token: 'ChmlFrpToken', publicOrigin: 'https://dsh.cwlindean.top' }
    expect(() => parseChmlFrpSettings({ ...base, user: 'short' })).toThrow('chmlfrp_user_invalid')
    expect(() => parseChmlFrpSettings({ ...base, user: 'bad user' })).toThrow('chmlfrp_user_invalid')
    expect(() => parseChmlFrpSettings({ ...base, user: 'user\nvalue' })).toThrow('chmlfrp_user_invalid')
    expect(() => parseChmlFrpSettings({ ...base, publicOrigin: 'http://dsh.cwlindean.top' })).toThrow('frp_public_origin_invalid')
    // Unknown fields must not be silently persisted.
    expect(() => parseChmlFrpSettings({ ...base, extra: 1 })).toThrow('chmlfrp_settings_invalid')
    expect(() => parseChmlFrpIni('')).toThrow('chmlfrp_ini_invalid')
    expect(() => parseChmlFrpIni(123)).toThrow('chmlfrp_ini_invalid')
  })

  it('dispatches on kind for either transport', () => {
    expect(parseFrpTransportSettings(JSON.parse(JSON.stringify(parseChmlFrpIni(PANEL_INI)))).kind).toBe('chmlfrp')
    expect(parseFrpTransportSettings({ serverAddress: 'frp.example.com', serverPort: 7000, token: '0123456789abcdef0123456789abcdef', publicOrigin: 'https://dsh.example.com' }).kind).toBe('self-hosted')
  })

  it('generates an INI for the client fork using the classic schema', () => {
    const settings = parseChmlFrpIni(PANEL_INI)
    const ini = createChmlFrpIni(settings, 39517)
    expect(ini).toContain('[common]')
    expect(ini).toContain('server_addr = 23.147.68.16')
    expect(ini).toContain('server_port = 7000')
    // ChmlFrp terminates no TLS and the loopback gateway already speaks HTTPS.
    expect(ini).toContain('tls_enable = false')
    expect(ini).toContain('user = 7iisbpYDIRLSmHqOcN8qwZDa')
    expect(ini).toContain('token = ChmlFrpToken')
    expect(ini).toContain('type = https')
    expect(ini).toContain('local_port = 39517')
    expect(ini).toContain('custom_domains = dsh.cwlindean.top')
    // Round-trips back to the same validated settings.
    expect(parseChmlFrpIni(ini)).toEqual(settings)
  })

  it('rewrites local_port to the port the gateway actually bound', () => {
    const rebound = bindChmlFrpIniLocalPort(createChmlFrpIni(parseChmlFrpIni(PANEL_INI), 443), 41000)
    expect(rebound).toContain('local_port = 41000')
    expect(rebound).not.toContain('local_port = 443')
    // Every other panel field survives untouched.
    expect(rebound).toContain('custom_domains = dsh.cwlindean.top')
    expect(rebound).toContain('user = 7iisbpYDIRLSmHqOcN8qwZDa')
    expect(() => bindChmlFrpIniLocalPort('[common]\nserver_addr = 1.2.3.4\n', 41000)).toThrow('chmlfrp_ini_invalid')
    expect(() => bindChmlFrpIniLocalPort('local_port = 443', 0)).toThrow('frp_local_port_invalid')
  })

  it('ignores comments and tolerates CRLF, spacing and section case', () => {
    const messy = '[COMMON]\r\n; comment\r\n# another\r\nserver_addr=23.147.68.16\r\nserver_port = 7000\r\nuser = 7iisbpYDIRLSmHqOcN8qwZDa\r\ntoken = ChmlFrpToken\r\n\r\n[dsh_mobile]\r\nlocal_port = 443\r\ncustom_domains = dsh.cwlindean.top\r\n'
    const settings = parseChmlFrpIni(messy)
    expect(settings.serverAddress).toBe('23.147.68.16')
    expect(settings.serverPort).toBe(7000)
    expect(settings.publicOrigin).toBe('https://dsh.cwlindean.top')
  })
})
